"""
harness/runtime/forgecad_adapter.py
====================================
ForgeCAD handoff adapter — real .forge.js emitter.

PRD §6.2: ``forgecad_emit`` generates editable ForgeCAD model code and
attaches previews, exports, and review notes.

This adapter emits a valid **ForgeCAD project** that engineers open with:
    npm install -g forgecad   (one-time setup)
    forgecad studio <project_dir>

The project contains:
    forge.config.json           — ForgeCAD project manifest
    models/<name>.forge.js      — parametric JavaScript model (live sliders)

Architecture note:
    CadQuery Python remains the OCCT-verified geometry authority used by the
    harness for volume, bounding-box, and watertightness checks.  The .forge.js
    file is generated in parallel by a dedicated LLM coder agent and is the
    engineer-facing editable surface.  Both artifacts are stored; the .forge.js
    is what the engineer opens in the ForgeCAD Studio workbench.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Optional

# Ensure CADSmith agents are importable from here
_PROJECT_ROOT = Path(__file__).resolve().parents[2]
_CADSMITH_DIR = _PROJECT_ROOT / "CADSmith"
if str(_CADSMITH_DIR) not in sys.path:
    sys.path.insert(0, str(_CADSMITH_DIR))

from autofab import agents  # noqa: E402

from harness.schema.primitives import PrimitivePlan


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def emit_forgecad_code(
    plan: PrimitivePlan,
    cadquery_code: str,
    prompt: str,
    *,
    trace_id: str,
    workflow_id: str,
    output_base_dir: str,
    step_artifact_uri: Optional[str] = None,
    stl_artifact_uri: Optional[str] = None,
    render_artifact_uri: Optional[str] = None,
    iteration: int = 0,
) -> tuple[str, str, dict]:
    """Generate a ForgeCAD .forge.js project and return (project_dir, js_source, metadata).

    Calls the ForgeCAD JS coder agent to produce parametric .forge.js source,
    then writes a valid ForgeCAD project structure to disk so that engineers
    can immediately open it with `forgecad studio <project_dir>`.

    Args:
        plan:              Validated PrimitivePlan from the planner agent.
        cadquery_code:     The verified CadQuery Python (kept as secondary artifact).
        prompt:            Original natural-language user prompt.
        trace_id:          Unique trace identifier for this run.
        workflow_id:       Temporal workflow ID.
        output_base_dir:   Base directory under which the project folder is created.
        step_artifact_uri: URI of the STEP artifact in the store (for metadata).
        stl_artifact_uri:  URI of the STL artifact in the store (for metadata).
        render_artifact_uri: URI of the render PNG in the store (for metadata).
        iteration:         Outer refinement loop iteration number.

    Returns:
        (project_dir, js_source, metadata)
        ``project_dir`` is the absolute path to the ForgeCAD project folder.
        ``js_source`` is the raw .forge.js source string.
        ``metadata`` contains all fields needed for the handoff API response.
    """
    # ── Generate .forge.js source via LLM agent ──────────────────────────
    design_plan_dict = plan.to_cadsmith_dict()
    js_source = agents.generate_forgecad_code(design_plan_dict, prompt)

    # ── Build project directory ──────────────────────────────────────────
    safe_name = (
        plan.description.lower()
        .replace(" ", "_")
        .replace("-", "_")[:40]
    )
    project_dir = Path(output_base_dir) / workflow_id / "forgecad" / safe_name
    models_dir = project_dir / "models"
    models_dir.mkdir(parents=True, exist_ok=True)

    # ── Write forge.config.json ──────────────────────────────────────────
    config = {
        "name": plan.description,
        "version": "1.0.0",
        "description": (
            f"Generated by Geometry Agent Harness | "
            f"workflow={workflow_id} | trace={trace_id} | iter={iteration}"
        ),
        "models": [f"models/{safe_name}.forge.js"],
        "metadata": {
            "workflow_id": workflow_id,
            "trace_id": trace_id,
            "iteration": iteration,
            "step_artifact_uri": step_artifact_uri,
            "stl_artifact_uri": stl_artifact_uri,
            "render_artifact_uri": render_artifact_uri,
        },
    }
    config_path = project_dir / "forge.config.json"
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")

    # ── Write the .forge.js model ────────────────────────────────────────
    js_header = _build_js_header(
        plan=plan,
        trace_id=trace_id,
        workflow_id=workflow_id,
        iteration=iteration,
        step_artifact_uri=step_artifact_uri,
        stl_artifact_uri=stl_artifact_uri,
        render_artifact_uri=render_artifact_uri,
    )
    js_full = f"{js_header}\n{js_source}\n"
    js_path = models_dir / f"{safe_name}.forge.js"
    js_path.write_text(js_full, encoding="utf-8")

    # ── Write studio launch hint (README.md in project) ──────────────────
    readme = _build_project_readme(
        plan=plan,
        project_dir=str(project_dir),
        workflow_id=workflow_id,
        trace_id=trace_id,
        iteration=iteration,
    )
    (project_dir / "README.md").write_text(readme, encoding="utf-8")

    metadata = {
        "workflow_id": workflow_id,
        "trace_id": trace_id,
        "design_name": plan.description,
        "iteration": iteration,
        "forgecad_project_dir": str(project_dir),
        "forgecad_model_file": str(js_path),
        "studio_launch_command": f"forgecad studio {project_dir}",
        "step_artifact_uri": step_artifact_uri,
        "stl_artifact_uri": stl_artifact_uri,
        "render_artifact_uri": render_artifact_uri,
        "components": plan.components,
        "acceptance_criteria": plan.acceptance_criteria.model_dump(),
        # Flag removed: real ForgeCAD .forge.js is now emitted
    }

    return str(project_dir), js_full, metadata


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _build_js_header(
    plan: PrimitivePlan,
    trace_id: str,
    workflow_id: str,
    iteration: int,
    step_artifact_uri: Optional[str],
    stl_artifact_uri: Optional[str],
    render_artifact_uri: Optional[str],
) -> str:
    """Build a JS block comment header prepended to the .forge.js source."""
    bbox = plan.dimensions.overall_bbox
    ac = plan.acceptance_criteria

    features_text = ""
    for feat in plan.features:
        features_text += f" *   [{feat.feature_type.value}] {feat.feature_id}: {feat.description}"
        if feat.count > 1:
            features_text += f" (×{feat.count})"
        features_text += "\n"
    if not features_text:
        features_text = " *   (no typed features in plan)\n"

    return f"""\
/**
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║  GEOMETRY AGENT HARNESS — ForgeCAD Model                            ║
 * ║  Open in ForgeCAD Studio:  forgecad studio .                        ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 *
 * Part        : {plan.description}
 * Workflow ID : {workflow_id}
 * Trace ID    : {trace_id}
 * Iteration   : {iteration}
 *
 * ── Dimensions ────────────────────────────────────────────────────────
 *   Envelope  : {bbox.xlen} × {bbox.ylen} × {bbox.zlen} mm
 *
 * ── Features ──────────────────────────────────────────────────────────
{features_text} *
 * ── Acceptance Criteria ───────────────────────────────────────────────
 *   Volume error   : ≤ {ac.volume_error_threshold_pct}%
 *   BBox IoU       : ≥ {ac.bbox_iou_threshold}
 *   Watertight     : {ac.require_watertight}
 *
 * ── Verified Artifacts (OCCT / CadQuery) ──────────────────────────────
 *   STEP   : {step_artifact_uri or "(pending)"}
 *   STL    : {stl_artifact_uri or "(pending)"}
 *   Render : {render_artifact_uri or "(pending)"}
 *
 * ── Notes ─────────────────────────────────────────────────────────────
 *   {plan.notes or "(none)"}
 *
 * HOW TO USE
 *   1. Run:  forgecad studio .
 *   2. Adjust parameter sliders to tune the geometry live.
 *   3. Export STEP/STL from the studio File menu.
 *   4. Full audit trail: look up trace_id in the artifact store.
 * ─────────────────────────────────────────────────────────────────────
 */
"""


def _build_project_readme(
    plan: PrimitivePlan,
    project_dir: str,
    workflow_id: str,
    trace_id: str,
    iteration: int,
) -> str:
    """Build a README.md for the ForgeCAD project folder."""
    return f"""\
# {plan.description}

Generated by **Geometry Agent Harness** | workflow `{workflow_id}` | iter {iteration}

## Open in ForgeCAD Studio

```bash
# One-time install (requires Node.js)
npm install -g forgecad

# Launch the live parametric editor
forgecad studio .
```

The studio opens in your browser with live parameter sliders for all dimensions.
Adjust, export STEP/STL, and iterate — no code recompile needed.

## Files

| File | Description |
|---|---|
| `forge.config.json` | ForgeCAD project manifest |
| `models/*.forge.js` | Parametric model — edit this |

## Verified Geometry Artifacts

The harness also produced OCCT-verified STEP and STL files.
Trace ID: `{trace_id}`  
"""
